version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flashcard_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: >
      --default-authentication-plugin=mysql_native_password
      --skip-log-bin
      --skip-host-cache
      --skip-name-resolve
      --innodb_use_native_aio=0
    networks:
      - flashcard_network

networks:
  flashcard_network:
    driver: bridge

volumes:
  mysql_data: